# Generated by Django 5.0.3 on 2024-04-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trickinstance",
            name="orientation",
        ),
        migrations.AddField(
            model_name="trickdefinition",
            name="trick_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trickinstance",
            name="right",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="trickinstance",
            name="trick_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="trickinstance",
            name="cab_slide",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="trickinstance",
            name="devil_twist",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="trickinstance",
            name="double_flipped",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="trickinstance",
            name="flipped",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="trickinstance",
            name="reverse",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="trickinstance",
            name="successful",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="trickinstance",
            name="twisted",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="trickinstance",
            name="twisted_exit",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
