# Generated by Django 5.0.3 on 2024-04-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0002_remove_trickinstance_orientation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="site",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="run",
            name="wing",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
