# Generated by Django 5.0.3 on 2024-04-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0006_remove_trickinstance_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trickinstance",
            name="user",
        ),
    ]
