# Generated by Django 5.0.3 on 2024-04-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0007_remove_trickinstance_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="trickdefinition",
            name="restrictions",
            field=models.JSONField(default=dict),
        ),
    ]
