# Generated by Django 5.0.3 on 2024-04-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0009_restriction_remove_trickdefinition_restrictions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trickdefinition",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
