# Generated by Django 5.0.3 on 2024-04-24 02:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0010_trickdefinition_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="trickdefinition",
            name="technical_coefficient",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="trickdefinition",
            name="reverse_bonus",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=4
            ),
        ),
    ]
