# Generated by Django 5.0.3 on 2024-05-06 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0012_trickdefinition_devil_twist_stall_bonus_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LastUsedTricks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_used", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "trick",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapi.trickdefinition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_used_tricks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "trick")},
            },
        ),
    ]
